
- name: Install OpenWhisk and wsk cli using helm
  hosts: servers
  tasks:
    - name: Set the OpenWhisk port
      shell:
        cmd: "wsk property set --apihost {{ow_install.stdout[ow_install.stdout.find(\"hostvars['server']['ansible_default_ipv4']['address']\"):][:ow_install.stdout[ow_install.stdout.find(\"hostvars['server']['ansible_default_ipv4']['address']\"):].find(\"\n\")]}}"