- name: Install k3s on the server node
  hosts: servers
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world
  
   - name: Install k3s on Server Node
     shell:
      "curl -sfL https://get.k3s.io | sh -"
     become: true

   - name: Get k3s Server Token
     shell:
      "sudo cat /var/lib/rancher/k3s/server/node-token"
     become: true
     register: token

- name: Install k3s on the agent nodes
  hosts: agents
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

   - name: Install k3s on Agent Nodes
     shell:
      cmd: "curl -sfL https://get.k3s.io | K3S_URL=https://{{hostvars['server']['ansible_default_ipv4']['address']}}:6443 K3S_TOKEN={{hostvars['server']['token'].stdout}} sh -"
     become: true

- name: Verify the installation
  hosts: servers
  tasks:
   - name: Check the status of teh installed k3s nodes
     shell:
      cmd: "sudo k3s kubectl get nodes"
     become: true
     register: status
     delegate_to: server
  
   - name: Show status content
     debug:
      var: status.stdout

   - name: Update Configuration location
     shell: 
      cmd: "mkdir .kube"
   
   - name: Update Configuration
     shell:
      cmd: "sudo cp /etc/rancher/k3s/k3s.yaml /home/sund/.kube/config"
     become: true
  
   - name: Set Ownership
     shell:
      cmd: "sudo chown sund:sund /home/sund/.kube/config"
     become: true 

- name: Install Knative
  hosts: servers
  tasks:
   - name: Installing Knative Serving custom ressources
     shell:
      cmd: "sudo kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.15.2/serving-crds.yaml"
     become: true

   - name: Installing Knative Serving core components
     shell:
      cmd: "sudo kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.15.2/serving-core.yaml"
     become: true

   - name: Download Kourier Yaml Manifest
     get_url: 
      url: https://github.com/knative/net-kourier/releases/download/knative-v1.15.1/kourier.yaml
      dest: "~/kourier.yaml"
    
   - name: Change from external load balancer to NodePort for local usage.
     ansible.builtin.replace:
      path: ~/kourier.yaml
      regexp: 'type: LoadBalancer'
      replace: 'type: NodePort'
   - name: add hardcoded nodePort 31080 for port 80
     ansible.builtin.replace:
      path: ~/kourier.yaml # Replace with the actual path to your YAML file
      regexp: '(\s+- name: http2\n\s+port: 80\n\s+protocol: TCP\n\s+targetPort: 8080)'
      replace: '\1\n      nodePort: 31080'
    
   - name: Installing the network layer of choice Kourier (Best for fit it all in Knative)
     shell:
      cmd: "sudo kubectl apply -f /home/sund/kourier.yaml"
     become: true
  
   - name: Configuring Kourier
     shell:
      cmd: "sudo kubectl patch configmap/config-network --namespace knative-serving --type merge --patch '{\"data\":{\"ingress-class\":\"kourier.ingress.networking.knative.dev\"}}'"
     become: true
  
   - name: Patch with {ansible host}.slip.io
     shell: |
       sudo kubectl patch configmap/config-domain \
       --namespace knative-serving \
       --type merge \
       --patch '{"data":{"{{ ansible_host }}.slip.io":""}}'
     become: true
  
   - name: Pause for 2 minutes to build network
     ansible.builtin.pause:
       minutes: 1

- name: Install hello world example
  hosts: servers
  tasks:
    - name: Copying the hello world example yaml to server node
      copy:
        src: ./hello.yaml
        dest: ~/hello.yaml
    
    - name: Applying the yaml in kubernetes cluster
      shell:
        cmd: "sudo kubectl apply -f hello.yaml"
      become: true