- name: My first play
  hosts: myhosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
      msg: Hello world
  
   - name: Install k3s on Server Node
     shell:
      "curl -sfL https://get.k3s.io | sh -"
     become: true
     delegate_to: server

   - name: Get k3s Server Token
     shell:
      "sudo cat /var/lib/rancher/k3s/server/node-token"
     become: true
     register: token
     delegate_to: server
  
   - name: Install k3s on Agent Nodes
     shell:
      cmd: "curl -sfL https://get.k3s.io | K3S_URL=https://{{hostvars['server']['ansible_default_ipv4']['address']}}:6443 K3S_TOKEN={{token.stdout}} sh -"
     become: true
     delegate_to: "{{ item }}"
     loop: "{{ groups['loadbalancers_group'] }}"

   - name: Install k3s on Agent Nodes
     shell:
      cmd: "curl -sfL https://get.k3s.io | K3S_URL=https://{{hostvars['server']['ansible_default_ipv4']['address']}}:6443 K3S_TOKEN={{token.stdout}} sh -"
     become: true
     delegate_to: agent2
  
   - name: Install k3s on Agent Nodes
     shell:
      cmd: "sudo k3s kubectl get nodes"
     become: true
     register: status
     delegate_to: server
  
   - name: Show token content
     debug:
      var: status.stdout